services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      # フロントエンドのソースコードをコンテナ内の/appディレクトリにマウント
      - ./app:/app
      # node_modulesディレクトリをコンテナ内に保持し、ホストのファイルシステムと同期しないようにする
      - /app/node_modules
